matrix:
  include:
  - os: linux
    language: generic
    sudo: required
    dist: trusty
    env: 
    - SWIFT_BRANCH=swift-4.2-convergence SWIFT_VERSION=swift-4.2-CONVERGENCE
    install:
    - mkdir swift
    - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null
    script:
    - env PATH=$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH swift build -c release
    - .build/release/tests
