language: generic
matrix:
  include:
  - os: osx
    env:
    - JOB="macOS + Swift Package Manager"
    osx_image: xcode10.1
    script:
    - swift run -c release tests
  - os: linux
    env:
    - JOB="Linux"
    dist: trusty
    script:
    - export SWIFT_VERSION=4.2.1
    - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
    - swift run -c release tests
  - os: linux
    env:
    - JOB="Miscellaneous"
    dist: trusty
    script:
    - export SWIFT_VERSION=4.2.1
    - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
    - bash "./Refresh (macOS).command"
    - bash "./Validate (macOS).command" •job miscellaneous
  - os: linux
    env:
    - JOB="Deployment"
    - secure: 
        ItOmb+XzkETMit+MCuuObTihtzfqdCrsmljxYWsJvicnZEchH0jKNrq2FOkLr4y1wPkzkU7FyCMsN2HRrFoEzaB6jTdybCm4uC11lNqlvCzhR6X3b7XtZydmiFN2lxTJWHiocj4LUlSUklxYAI6WikavU6h1xA19wF8lH+mH05IWQ9sxtW/FE0DGcqiZVCXHDJYDNaeYSDgbj2xzgpmaJ8qiea+CbTQfo5RqYtImDcby/S9NnHoKM8vw3Sxoodj0EtS7sc/T6ZXCHsxJ6v69dMuC25RBwp6vmyAqP5pFU17unB5x1wQo0Wj9wqPU+C2599ACAYS1T091uWNGRO55xgi8c6Npg0Aj89yV8UT8wYZAmfHEvTgEaUfATMG2Whc0nHOm/2sU2R78SfxXOrCKnQvGwWFEq50SWilUHpvUrGExZe4Pk3zlmCogrWweEuiBzlU7RnWA8YgYiC++MOs1LBfoH3Z/e8/k2o/cvS6jU04AGB0kaQBDS2NxaPSYCSpbFt62BdaSkGMdysze7h6028PNIz0fdCVFuMgu78Pjd9SiApjvfoOrJkuw3PHzUEerpgC5rMgx4aWwfUDbs3+YXnrZVaNLScmSMycr67/drFb6QqQC2uSsQvq2PLoldsm8Ct28CnB2UBxj5t1OyZJ1gWF7Il0I1Sfvr0RspxiT9p4=
    if: branch = master and (not type = pull_request)
    deploy:
      provider: pages
      local_dir: docs
      github_token: "$GITHUB_TOKEN"
      skip_cleanup: true
    dist: trusty
    script:
    - export SWIFT_VERSION=4.2.1
    - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
    - bash "./Refresh (macOS).command"
    - bash "./Validate (macOS).command" •job deployment
cache:
  directories:
  - "$HOME/Library/Caches/ca.solideogloria.Workspace"
  - "$HOME/.cache/ca.solideogloria.Workspace"
