name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    # reads .swift-version
    - uses: YOCKOW/Action-setup-swift@master
    - env:
        destination: $
        DEVELOPER_DIR: '/Applications/Xcode_11.1.app/Contents/Developer'
      run:  | 
        swift run             unit-test 
        swift run -c release  integration-test 
        swift run -c release  compression-test 
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: YOCKOW/Action-setup-swift@master
    - run:  | 
        swift run             unit-test 
        swift run -c release  integration-test 
        swift run -c release  compression-test 
